language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script: pyinstaller --onefile --name flame -- main.py
deploy:
  provider: releases
  api_key:
    secure: b654c6b8d044152d2611ad49476293cf59fab31f
  file: "dist/flame"
  skip_cleanup: true
  on:
    tags: true