#!/bin/bash

echo "Installing Flame..."
mkdir flame-inst
cd flame-inst
echo "Clone GitHub repository..."
git clone https://github.com/Stylix58/flame
cd /flame
echo "Installing PyInstaller..."
pip3 install pyinstaller
echo "Compiling Flame..."
pyinstaller --onefile --name flame -- main.py
cd dist
mv flame ../../../flame/
echo "Installation finished!"
echo "WARNING: You need to change Flame of directory. You need to do that before removing files and folders generated by Flame auto-install."
echo "For make this task, just type in this terminal (you need to have sudo rights): sudo mv /flame-inst/flame /usr/bin/flame"
